# Generated by Django 5.0.2 on 2024-02-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('stop_loss', models.FloatField()),
                ('first_target', models.FloatField()),
                ('second_target', models.FloatField()),
                ('target_met', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('bullish', 'Bullish'), ('futures_options', 'Futures & Options'), ('previous_week', 'Previous Week Performance')], max_length=16)),
            ],
        ),
    ]
